### ISSUE TITLE
OrientJdbcDatabaseMetaData must be modified in order to be supported by liquibase 3.1.1

### ISSUE THREAD

**Issue by young-druid** [orientechnologies/orientdb-jdbc#11]
The following methods should be modified in OrientJdbcDatabaseMetaData.java
```java
public String getSQLKeywords() throws SQLException;
public ResultSet getTables(String catalog, String schemaPattern, String tableNamePattern, String[] types) throws SQLException;
public ResultSet getTableTypes() throws SQLException;
```
I am going to send a pull request in a few days but could you clarify a few items before I proceed:
1. Can I rely on [this](https://raw.githubusercontent.com/wiki/orientechnologies/orientdb/SQL-Syntax.md) document when generating keywords?
2. Is that right that there is only two types of tables in OrientDB:
* TABLE
* SYSTEM TABLE

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5181
