### ISSUE TITLE
Please make jdbc-all JAR available on Maven

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb-jdbc#21]
While the pure JDBC driver is available, it would be much simpler for projects that want to use Orient DB via JDBC if we could import jdbc-all via Maven (same applies to importing the driver into various graphical tools like IDEs and DB navigators).  One step import is a significantly lower barrier to entry.

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5177
