### ISSUE TITLE
PreparedStatement.execute() ignores binded parameters

### ISSUE THREAD

**Issue by aponcon** [orientechnologies/orientdb-jdbc#23]
Actually, only PreparedStatement.executeQuery() and PreparedStatement.executeUpdate() apply the parameters.
But PreparedStatement.execute()  doesn't override the one defined in Statement class (which of course doesn't suppport parameters).

As some libraries like JDBI are only relying on PreparedStatement.execute() to make prepared statements, it can be quite annoying.

**Comment by lvca** [comment]
Merged, thanks
