### ISSUE TITLE
resultSet.getMetaData ().getColumnType (INDEX) throws NPE

### ISSUE THREAD

**Issue by daanv1987** [orientechnologies/orientdb-jdbc#29]
When an JDBC query doesn't return any data the resultSet.getMetaData ().getColumnType (index) throws an NPE.

This is due to the following lines in the ```OrientJdbcResultSetMetaData.java``` file.
```java
ODocument currentRecord = this.resultSet.unwrap(ODocument.class);
final String[] fieldNames = currentRecord.fieldNames(); // current record == null
```

There is no current record. The only exception that should be thrown by ```getColumnType``` is an SQLException, so I propose at least a null check and SQLException with clear exception text. 

Perhaps for a more comprehensive solution this metadata can be retrieved from the schema (with java.sql.Types.OTHER for run time properties?) when empty ResultSets are returned.

A way to reproduce this:
```java
OrientGraphNoTx graph = new OrientGraphNoTx ("plocal:./database");

OClass data = graph.createVertexType ("Data");
data.createProperty ("name", OType.STRING).setMandatory (true).setNotNull (true);
        
graph.commit ();
        
Properties info = new Properties();
info.put("user", "admin");
info.put("password", "admin");
        
Class.forName("com.orientechnologies.orient.jdbc.OrientJdbcDriver");
Connection connection = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:plocal:./database", info); 
Statement statement = connection.createStatement (); 
ResultSet resultSet = statement.executeQuery ("select name from Data");
        
resultSet.getMetaData ().getColumnType (1); // Throws NPE 
```

**Comment by lvca** [comment]
Fixed, thanks for the report.
